[workspace]
authors = ["maxreith <max.reith@gmx.de>"]
channels = ["conda-forge"]
name = "the_game_simulation"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13,<3.14"
numpy = ">=2.3.5,<3"
pytest = ">=9.0.1,<10"
ipykernel = ">=7.1.0,<8"
pathlib = ">=1.0.1,<2"
snakeviz = ">=2.2.2,<3"
jupyterlab = ">=4.5.0,<5"
line_profiler = ">=5.0.0,<6"
pandas = ">=2.3.3,<3"
pyarrow = ">=22.0.0,<23"
google-genai = ">=1.56.0,<2"
pydantic = ">=2.12.5,<3"
typing = ">=3.10.0.0,<4"
python-dotenv = ">=1.2.1,<2"
matplotlib = ">=3.10.8,<4"
pytask = ">=0.5.8,<0.6"

[pypi-dependencies]
pdbp = "*"
